POST http://localhost:3003/api/blogs
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJlbXBwcGEiLCJpZCI6IjY5ODFmZWFmZjgxZmMyNzdhYjMyNDc5NCIsImlhdCI6MTc3MDEyOTgxNywiZXhwIjoxNzcwMTMzNDE3fQ.0VgYd_2BEqyP2FeQxwX7nl0Q5AAfQnQPvRKw9z6TC91

{
    "title": "Trapped in the hell of social comparison",
    "author": "Noah Smith",
    "url": "https://www.noahpinion.blog/p/trapped-in-the-hell-of-social-comparison",
    "likes": 428
}